# Generated by Django 5.1.4 on 2025-01-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, default='default-category.png', null=True, upload_to='category_pics/')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(editable=False, max_length=9, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('image', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('language', models.CharField(default='English', max_length=20, verbose_name=(('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu')))),
                ('level', models.CharField(default='Beginner', max_length=20, verbose_name=(('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')))),
                ('instructor_status', models.CharField(default='Draft', max_length=20, verbose_name=(('Draft', 'Draft'), ('Published', 'Published'), ('Disabled', 'Disabled')))),
                ('platform_status', models.CharField(default='Review', max_length=20, verbose_name=(('Review', 'Review'), ('Rejected', 'Rejected'), ('Approved', 'Approved')))),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.instructor')),
            ],
        ),
    ]
