# Generated by Django 5.1.4 on 2025-01-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_country_cart_cartorder_certificate_chapter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Cart Order'},
        ),
        migrations.AlterModelOptions(
            name='cartorderlist',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Cart Order List'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': 'Chapter'},
        ),
        migrations.AlterModelOptions(
            name='chapterlist',
            options={'verbose_name_plural': 'Chapter List'},
        ),
        migrations.AlterModelOptions(
            name='completedlesson',
            options={'verbose_name_plural': 'Completed Lessons'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='enrolledcourse',
            options={'verbose_name_plural': 'Enrolled Course'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': 'Instructor'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='question_answer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Question and Answer'},
        ),
        migrations.AlterModelOptions(
            name='question_answer_message',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Question Answer Message'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
